//
//  InfoViewController.swift
//  Bitcoin Rate
//
//  Created by Apple on 3/29/20.
//  Copyright © 2020 ForZa. All rights reserved.
//

import UIKit

class InfoViewController: UIViewController {

    let bitcoinImageView: UIImageView = {
        let imageView = UIImageView(image:  #imageLiteral(resourceName: "BitcoinGold"))
        imageView.translatesAutoresizingMaskIntoConstraints = false
        return imageView
    }()
    
    let descriptionTextView: UITextView = {
        let textView = UITextView()
    
        let attributedText = NSMutableAttributedString(string: "What is BTC, ETH, XRP?", attributes: [NSMutableAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 18)])
        
        attributedText.append(NSAttributedString(string: "\n\n BTC - Bitcoin", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 15), NSAttributedString.Key.foregroundColor: UIColor(named: "ColorGold")!]))
        
        attributedText.append(NSAttributedString(string: "\nBitcoin is a cryptocurrency.It is a decentralized digital currency without a central bank or single administrator that can be sent from user to user on the peer-to-peer bitcoin network without the need for intermediaries.", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 14), NSAttributedString.Key.foregroundColor: UIColor.gray]))
        
        attributedText.append(NSAttributedString(string: "\n\n ETH - Etherium", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 15), NSAttributedString.Key.foregroundColor: UIColor(named: "ColorGold")!]))
        
        attributedText.append(NSAttributedString(string: "\nThe cryptocurrency generated by the Ethereum platform as a reward to mining nodes for computations performed and is the only currency accepted in the payment of transaction fees.", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 14), NSAttributedString.Key.foregroundColor: UIColor.gray]))
        
        attributedText.append(NSAttributedString(string: "\n\n XRP - Ripple", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 15), NSAttributedString.Key.foregroundColor: UIColor(named: "ColorGold")!]))
        
        attributedText.append(NSAttributedString(string: "\nThe ledger employs the decentralized native cryptocurrency known as XRP, which as of September 2018 was the second largest coin by market capitalization.", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 14), NSAttributedString.Key.foregroundColor: UIColor.gray]))
        
        textView.attributedText = attributedText
        textView.textAlignment = .center
        textView.isEditable = false
        textView.isScrollEnabled = false
        textView.translatesAutoresizingMaskIntoConstraints = false
        textView.backgroundColor = UIColor(named: "Color")
        return textView
    }()

    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.addSubview(bitcoinImageView)
        view.addSubview(descriptionTextView)
        
        setupLayout()
    }


    func setupLayout() {
        bitcoinImageView.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive        = true
        bitcoinImageView.topAnchor.constraint(equalTo: view.topAnchor, constant: 100).isActive = true
        bitcoinImageView.widthAnchor.constraint(equalToConstant: 200).isActive                 = true
        bitcoinImageView.heightAnchor.constraint(equalToConstant: 200).isActive                = true
        
        descriptionTextView.topAnchor.constraint(equalTo: bitcoinImageView.bottomAnchor, constant: 30).isActive = true
        descriptionTextView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 24).isActive         = true
        descriptionTextView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -24).isActive      = true
        descriptionTextView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: 0).isActive            = true
    
    }

}
